### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by alexeybozhchenko** [SamYuen101234/Masked_Face_Recognition#12]
Greetings! Thank you for this useful contribution. 
How can I try this out? I.e. you provided 3 models, is there a script for the inference? You also provide a link to some gh repo where you used it, but the link is broken.  Or maybe you could give me a hint so I can get it running. Since we are talking about face recognition, I assume that somewhere gotta be a part where I build a face embedding and use some distance metric. Is that correct?

**Comment by SamYuen101234** [comment]
Sorry for late reply. You should clone all the python script first and then download the 3 models from google drive and put them in a folder called "models". Also, you should download the datasets from the links that I provided. Then, you can run it with python3 main.py. This is only a repo for training a masked facial recognition model not a facial recognition system. You need to use the model to build your own facial recognition system.
