### ISSUE TITLE
How to modify the location of th data in this project?

### ISSUE THREAD

**Issue by sja9527** [SamYuen101234/Masked_Face_Recognition#15]
Thanks for your good job!  I have download the data, but i do not know how to use it. In your code,how to modify it?

**Comment by SamYuen101234** [comment]
put the data folders with the script under the same directory and then run python3 main2.py for ArcFace option.

**Comment by sja9527** [comment]
Thanks for your reply. it is so amazing! can you show me the whole structure of this project?  For i can not understand 'put the data folders with the script under the same directory'  immediately

**Comment by SamYuen101234** [comment]
put the data folders e.g. train/test like this
![Screenshot 2021-06-01 at 4 17 38 PM](https://user-images.githubusercontent.com/43022742/120290487-f600fa00-c2f4-11eb-9e00-b1fd702cb3ad.png)

**Comment by SamYuen101234** [comment]
the Code folder in the github repository can be ignored, that is the code of my teammate but the code  is the same as the outer most directory's code.

**Comment by sja9527** [comment]
Got it! I am a student. I want to change wechat or QQ with you, if you do not feel disturbed

**Comment by sja9527** [comment]
Can you show me the structure of  the folder: 'train'? while i use train,use the train2 too?

**Comment by SamYuen101234** [comment]
You can add my QQ 1015309283 or wechat yuanzhikun747903

**Comment by SamYuen101234** [comment]
You should use both train and train2 as training dataset, the whole train.csv includes both datasets
