### ISSUE TITLE
How to use the real face dataset to test the train model?

### ISSUE THREAD

**Issue by small-seven** [SamYuen101234/Masked_Face_Recognition#16]
I found that the images in the train, eval, test set have the size of 128x128. However, the images in the real masked face dataset have diverse sizes. How to use the real masked face dataset to test the model trained with images of size 128x128?

**Comment by SamYuen101234** [comment]
use mtcnn to do face detection and alignment, and then use the resize function in torch.transforms to interpolate the images

**Comment by small-seven** [comment]
Got it. Thank you for your reply.
