### ISSUE TITLE
When does "collapse" happens?

### ISSUE THREAD

**Issue by yh97yhyh** [SamYuen101234/Masked_Face_Recognition#21]
Hello!
I ran this code, but I had met "collapse" when 1epoch was over. (I edited code...)
When does "collapse" happens? and How can I solve this problem?

**Comment by SamYuen101234** [comment]
Do you try some models pre-trained on ImageNet or VGG2?

**Comment by yh97yhyh** [comment]
No, How can I try these models?

**Comment by yh97yhyh** [comment]
> Do you try some models pre-trained on ImageNet or VGG2?

Do you mean these models?
<img width="913" alt="스크린샷 2022-03-16 오후 5 07 40" src="https://user-images.githubusercontent.com/47898473/158545343-f30012e5-91f0-49a6-85ab-29e2d85c77df.png">

I just tried main.py and main2.py after put csv file, train and test dataset.
I didn't use these pre-trained models.

**Comment by SamYuen101234** [comment]
Do you set the parameter "pretrained" = True ? And what Model do you use. If you set pretrained = True, the models are pretrained on ImageNet/VGG2 are used.

**Comment by yh97yhyh** [comment]
Thanks! I'll give it a try!

**Comment by SamYuen101234** [comment]
closed

**Comment by SamYuen101234** [comment]
closed
